export const CHARACTER_SIGNATURE_WEAPONS: Record<string, string> = {
  "diluc": "wolf-s-gravestone",
  "jean": "aquila-favonia",
  "mona": "skyward-atlas",
  "keqing": "primordial-jade-cutter",
  "qiqi": "aquila-favonia",
  "tighnari": "hunter-s-path",
  "dehya": "beacon-of-the-reed-sea",
  "albedo": "cinnabar-spindle",
  "kinich": "mountain-bracing-bolt",
  "venti": "elegy-for-the-end",
  "klee": "lost-prayer-to-the-sacred-winds",
  "ganyu": "amos-bow",
  "xiao": "primordial-jade-winged-spear",
  "tartaglia": "polar-star",
  "zhongli": "vortex-vanquisher",
  "hu-tao": "staff-of-homa",
  "eula": "song-of-broken-pines",
  "kaedehara-kazuha": "freedom-sworn",
  "kamisato-ayaka": "mistsplitter-reforged",
  "yoimiya": "thundering-pulse",
  "raiden-shogun": "engulfing-lightning",
  "sangonomiya-kokomi": "everlasting-moonglow",
  "arataki-itto": "redhorn-stonethresher",
  "shenhe": "calamity-queller",
  "yae-miko": "kagura-s-verity",
  "kamisato-ayato": "haran-geppaku-futsu",
  "yelan": "aqua-simulacra",
  "cyno": "staff-of-the-scarlet-sands",
  "nilou": "key-of-khaj-nisut",
  "nahida": "a-thousand-floating-dreams",
  "wanderer": "tulaytullah-s-remembrance",
  "alhaitham": "light-of-foliar-incision",
  "baizhu": "jadefall-s-splendor",
  "lyney": "the-first-great-magic",
  "neuvillette": "tome-of-the-eternal-flow",
  "wriothesley": "cashflow-supervision",
  "furina": "splendor-of-tranquil-waters",
  "navia": "verdict",
  "xianyun": "crane-s-echoing-call",
  "chiori": "uraku-misugiri",
  "arlecchino": "crimson-moon-s-semblance",
  "clorinde": "absolution",
  "sigewinne": "silvershower-heartstrings",
  "emilie": "lumidouce-elegy",
  "mualani": "surf-s-up",
  "xilonen": "peak-patrol-song",
  "chasca": "astral-vulture-s-crimson-plumage",
  "mavuika": "a-thousand-blazing-suns",
  "citlali": "starcaller-s-watch",
  "varesa": "vivid-notions",
  "escoffier": "symphonist-of-scents",
  "skirk": "azurelight",
  "ineffa": "fractured-halo",
  "lauma": "nightweaver-s-looking-glass",
  "flins": "bloodsoaked-ruins",
  "nefer": "reliquary-of-truth",
  "durin": "athame-artis",
  "columbina": "nocturne-s-curtain-call",
  "zibai": "lightbearing-moonshard",
  "varka": "skyward-atlas",
  "lohen": "disaster-and-remorse",
  "linnea": "astral-vulture-s-crimson-plumage",
  "nicole": "athame-artis",
  "sandrone": "starcaller-s-watch",
  "odette": "whitelake-frostfeather",
};

export function getSignatureWeaponSlug(characterSlug?: string | null): string | null {
  if (!characterSlug) return null;
  const lower = characterSlug.toLowerCase().trim();
  const kebab = lower.replace(/_/g, "-");
  return CHARACTER_SIGNATURE_WEAPONS[kebab] ?? CHARACTER_SIGNATURE_WEAPONS[lower] ?? null;
}
